---
title: "Desigualdad, política y lenguaje"
subtitle: "El rol del manejo del lenguaje en la transmisión intergeneracional de las habilidades políticas en jóvenes chilenos"
csl: "../input/bib/apa6.csl"
bibliography: "../input/bib/zlibrary.bib"
author: " "
output:
    html_document:
        smart: false
        includes:
          in_header: head_github-activity.html
---
<div style="text-align: justify">

# Resumen: 

Actualmente las democracias se encuentran frente a crisis de legitimidad que se relacionan, entre otras cosas, con la falta de representación de distintos grupos, como los sectores populares y los jóvenes. Al respecto, las investigaciones han señalado que no solo existen diferencias actitudinales hacia la política según grupo social, sino que también existen brechas en las habilidades políticas que se relacionan con la participación desigual. La asociación internacional para la evaluación del logro educativo (IEA) ha desarrollado el Estudio Internacional de Educación Cívica y Formación Ciudadana (ICCS) que se enfoca en estudiar las Habilidades y Conocimientos necesarios para la vida ciudadana en jóvenes estudiantes. El conocimiento cívico de la ICCS ha generado interés en distintos investigadores puesto que se asocia positivamente con un conjunto de actitudes democráticas como la participación y la tolerancia. Se ha demostrado que existe una relación entre nivel socioeconómico y conocimiento Cívico. Al explicar esta desigualdad algunos autores han señalado que en familias de alto capital cultural se genera un ambiente más ciudadano y académico, que implica una socialización en valores políticos y habilidades cognitivas. Para profundizar esta línea de investigación, se propone que parte de lo que explica la relación entre desigualdad social y conocimiento cívico es el manejo del lenguaje. Para evaluar esta hipótesis se trabajaron conjuntamente los datos de la ICCS y el SIMCE (N = 3140). A partir de los análisis de mediación multinivel, se concluye que la transmisión intergeneracional de la desigualdad política se explica más por habilidades en el lenguaje que por la transmisión de intereses políticos. Además, se evidencia el potencial del lenguaje para disminuir la desigualdad de habilidades políticas, lo cual puede ser provechoso para la implementación del ramo de formación ciudadana.

__Palabras clave: Conocimiento Cívico, Desigualdad política, Comprensión lectora, Interés político__


## ¿Como acceder al Articulo?.

Para visualizar el documento haga click en la parte superior derecha, ya sea en "Articulo en linea" o en "Descargar en PDF"


### Profesor guía:

-  Juan Carlos Castillo, Departamento de Sociología, Universidad de Chile. [juancastillov@uchile.cl](juancastillov@uchile.cl), [jc-castillo.com](http://jc-castillo.com/)


### Reproductivilidad y documentacion.

The repository of the project in Github is structured according to the [IPO reproducibility protocol](https://juancarloscastillo.github.io/ipo/).


